### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by mlisocialure** [mlisocialure/thinkful-node-course#1]
@WilliamHoang: please take a look at this script to see what is going on with the bugs? thx.

**Comment by WilliamHoang** [comment]
@mlisocialure :  Take a look at how to access the contents from within a Dictionary.  Understand the key:value structure and also how it is used within a 'for-loop'

**Comment by mlisocialure** [comment]
@WilliamHoang : I managed to make the code work by correcting a typo in the second for in loop.
So this thing is working now (updated working code in this commit, pls review) despite the problem you pointed out. I did find another solution on stackoverflow using reduce that is much simpler and sidestep the problem with the loop entirely.
Do you want me to post that solution in a separate commit?

**Comment by WilliamHoang** [comment]
@mlisocialure :  If you forgo the loop, then there are only two properties to look at, price1 & price2, for each customer and that changes your reference to customer base.

I would say having one simple working solution is suffice and then look at optimizing the code overall.  You can put it as a separate file within the folder for review and discussion.  Good practice with different solutions.

**Comment by mlisocialure** [comment]
@WilliamHoang : uploaded the other solution under unit1, much more efficient FP style solution using Reduce.
