### ISSUE TITLE
HTTP server

### ISSUE THREAD

**Issue by mlisocialure** [mlisocialure/thinkful-node-course#2]
@WilliamHoang: Hi William, can we meet up over skype next Monday 11 AM again to go over unit 2? I will see how far I can get on my own and ask you the questions I have. I am still getting used to how js works on the server side.

Thanks!

**Comment by mlisocialure** [comment]
@WilliamHoang:

I am not clear about this section:
https://courses.thinkful.com/node-001v4/assignment/2.1.3

Try using your client to make requests to your echo server. Make sure that the correct headers are being set by the server and the information being returned is correct. Note that you will need to have the server and client running in separate terminals.
"
Open 2 terminals. In one, cd into hello_client and in the other cd into hello_server
Run the server
Change the hello_client to make a request to your hello_server. The server should be available at the same temporary URL from earlier
Have the hello_client make a request to each route in the server, and log the results."

**Comment by WilliamHoang** [comment]
@mlisocialure :  We are on the calendar for 8/22 at 11AM PST time currently.  Happy to answer questions you have then too.

**Comment by WilliamHoang** [comment]
@mlisocialure:  Regarding your question in the [material](https://courses.thinkful.com/node-001v4/assignment/2.1.3) the terminals are representing a client (eg. webapp) and a server (eg. nodejs running on aws) You would then make the association links.  When you are running your server, it would be working in the background.  When a call is request via HTTP from the client, it would reference an endpoint that the server code is located (temp url)

Hope that helps!
William

**Comment by mlisocialure** [comment]
@WilliamHoang : and this was the other question I wanted to ask you:

I want to build a simple web app, where the client side is just a simple input field, where one types in a message eg "happy birth William" with some html changing font, color of text etc, which is then displayed in a separate page via the server, that can be opened from another computer, phone etc.

The code I have here inputs the message on the server side, can I just build a front end text field box that access the message typed below? I am thinking about ways to do that.

---

var express = require('express');

var app = express();

app.get('/', function(request, response) {
    response.send(<b><font color=”#0099ff”'> "Happy Birthday William" </font></b>);
});

---

Once this is done I will just deploy it onto Heroku.

**Comment by mlisocialure** [comment]
@WilliamHoang: Found this that may help me to send data to the server via express while storing it in DB.
https://github.com/mysqljs/mysql

It is written by a guy working at Alipay (Alibaba) in Hangzhou, China!
