### ISSUE TITLE
server.js keeps getting "cannot GET" error message

### ISSUE THREAD

**Issue by mlisocialure** [mlisocialure/thinkful-node-course#4]
@WilliamHoang:
Per 
https://github.com/mlisocialure/thinkful-node-course/blob/master/bottle_app/express.js

can you take a look of why my server is still not getting anything from "login"? Thanks.

**Comment by WilliamHoang** [comment]
@mlisocialure :  Sure I will and I will put this in my queue for tomorrow morning to look at.

**Comment by WilliamHoang** [comment]
@mlisocialure :  This looks correct, one thing is to do a log in your login page so anything that accesses the path then you can see it printed or check the return status code too.

**Comment by mlisocialure** [comment]
@WilliamHoang : found the reason. The static html file was not named index. When I rename it to index.html the problem goes away.
