### ISSUE TITLE
Why mocha test keeps running into timeout error?

### ISSUE THREAD

**Issue by mlisocialure** [mlisocialure/thinkful-node-course#5]
@WilliamHoang:

I don't know why I keep running into timeout errors with tests that I basically copied from course material...

https://github.com/mlisocialure/thinkful-node-course/blob/master/shopping-list/test/test-server.js

**Comment by WilliamHoang** [comment]
@mlisocialure :  Do you have a print screen of the command you executed and the returns or hangs you are receiving?

**Comment by mlisocialure** [comment]
@WilliamHoang:

mlisocialure:~/workspace/mongo-shopping-list/test $ mocha test-server.js

error message reproduced below: 

---

Listening on port 8080
  1) should list items on GET
  2) should add an item on POST

  0 passing (4s)
  2 failing

  1)  should list items on GET:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  2)  should add an item on POST:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by mlisocialure** [comment]
@WilliamHoang: 
Also for the chai test here:
https://github.com/mlisocialure/thinkful-node-course/blob/master/unit2/test/test-server.js

TypeError: Cannot read property 'address' of undefined”
1) Shopping List should list items on GET:
     TypeError: Cannot read property 'address' of undefined
      at serverAddress (/home/ubuntu/workspace/thinkful-node-course/unit2/node_modules/chai-http/lib/request.js:252:17)
      at new Test (/home/ubuntu/workspace/thinkful-node-course/unit2/node_modules/chai-http/lib/request.js:244:53)
      at Object.obj.(anonymous function) [as get](/home/ubuntu/workspace/thinkful-node-course/unit2/node_modules/chai-http/lib/request.js:216:14)
      at Context.<anonymous> (test-server.js:14:8)
